version: '2'
services:
  cassandra:
    image: cassandra:2.2
    ports:
      - "9042"
  dataportenschemas:
    image: registry.uninett.no/public/dataporten-cassandra-schemas
    links:
      - cassandra:cassandra
    environment:
      - CASSANDRA_NODE=cassandra
      - CASSANDRA_KEYSPACE=dataporten
      - TESTDATA=true
    command: up
  metadataschemas:
    image: registry.uninett.no/public/dataporten-cassandra-schemas
    links:
      - cassandra:cassandra
    environment:
      - CASSANDRA_NODE=cassandra
      - CASSANDRA_KEYSPACE=metadata
      - SCHEMA=metadata
    command: up
  testenv:
    build: testenv
    links:
      - cassandra:cassandra
    volumes:
      - .:/authengine
      - ./etc/authengine/config.json:/authengine/etc/config.json
      - ./test-config/jwt-cert.pem:/conf/jwt-cert.pem
      - ./test-config/jwt-key.pem:/conf/jwt-key.pem
      - ./test-config/testusers.json:/authengine/etc/testusers.json
    environment:
      - FC_CASSANDRA_CONTACTPOINTS=cassandra
      - FC_CASSANDRA_USESSL=false
      - FC_CASSANDRA_KEYSPACE=dataporten
      - FC_CASSANDRA_SESSION_KEYSPACE=session
      - AE_TESTUSERSFILE=testusers.json
